### ISSUE TITLE
不知道能有什么方法做出zabbix上面的top 10?

### ISSUE THREAD

**Issue by kingcmy** [yrjsg/ZabbixQuestionList#6]
楼主你好，我主要是想监控cpu、memory、disk I/O、network几个部分
想整理出目前资产中使用最高的前10项并且展示出来，展示的途径可以是修改dashboard来展示，也可以定期发送邮件展示。。
但是目前还没有什么好的思路，有看过别人写的一些通过数据库抓取排序再展示的文章，但是觉得通过sql这种方式很麻烦很麻烦，所以想问你请教一下有没有什么方法可以实现？

**Comment by yrjsg** [comment]
只有用sql
